### ISSUE TITLE
After latest Hydro updates, catkin_make fales on /opt/ros/hydro/lib/python2.7/dist-packages/qt_create/templates/qt-ros/package.xml

### ISSUE THREAD

**Issue by koenlek** [stonier/qt_ros#10]
After installing latest updates for Hydro (on 12.04, x64), all my catkin workspaces failed to compile. Even after rebooting, reinstalling all ros packages, creating new ws, etc. 

Please also see my question and the discussion here:
http://answers.ros.org/question/174736/since-updating-ros-a-few-hours-ago-roscatkin-is-broken/

It turns out that  a CATKIN_IGNORE file was indeed not present under `/opt/ros/hydro/lib/python2.7/dist-packages/qt_create/templates/qt-ros/`, creating it solved the problem for me. Is this a qt_ros issue? Or a catkin, or some other issue?

Kind regards,
Koen

**Comment by stonier** [comment]
Looks like a `qt_ros` issue now that catkin is parsing those directories as well. 

Fixed in 9c12f3f5dd171d8f82a281d13686e9cf8a4d8fa1. Releasing in 0.2.6.

Thanks for the heads up.
