### ISSUE TITLE
ros-hydro-qt-create package breaks workspace builds

### ISSUE THREAD

**Issue by roehling** [stonier/qt_ros#11]
The error message is as follows:

```
CMake Error at /home/roehling/ros/build/catkin_generated/order_packages.cmake:2 (message):
  Invalid package manifest
  /opt/ros/hydro/lib/python2.7/dist-packages/qt_create/templates/qt-ros/package.xml":
  Package name "%(package)s does not follow naming conventions

  Invalid email %(author)s@gmail.com" for person "%(author)s""
Call Stack (most recent call first):
  /opt/ros/hydro/share/catkin/cmake/catkin_workspace.cmake:36 (include)
  toplevel.cmake:63 (catkin_workspace)
  CMakeLists.txt:21 (include)


-- Configuring incomplete, errors occurred!
```

The problem is that the templates folder contains a malformed `package.xml`, which is picked up by the build system. Possible workarounds:
- a `CATKIN_IGNORE` file put into the `/opt/ros/hydro/lib/python2.7/dist-packages/qt_create/templates` folder
- renaming the templated `package.xml` to e.g. `package.xml.in`, so it is no longer processed by catkin

**Comment by stonier** [comment]
Already in shadow-fixed....see #10.

**Comment by roehling** [comment]
Sorry, I forgot to check the closed issues. Beginner's mistake. :-)
