### ISSUE TITLE
catkin_create_qt_project creates wrong package.xml if deps given

### ISSUE THREAD

**Issue by strothmw** [stonier/qt_ros#14]
If i run catkin_create_qt_project my_project cv_brigde sensor_msgs it adds to package.xml for deps:

`<depend package="cv_brigde"/>`
`<depend package="sensor_msgs"/>`

rather than

`<build_depend>cv_brigde</build_depend>`
`<build_depend>sensor_msgs</build_depend>`
`<run_depend>cv_brigde</run_depend>`
`<run_depend>sensor_msgs</run_depend>`

I am under ros hydro with ubuntu 12.04 64 bit

**Comment by stonier** [comment]
Thanks for the heads up...I'll have a look at this mid september'ish when I get some time (or you can send a pull request :neckbeard: ).
