### ISSUE TITLE
Using qwt with this package

### ISSUE THREAD

**Issue by AlanTurnage** [stonier/qt_ros#15]
What do I have to do to use qwt with your package? I have a gui up and running and everything works except the qwt compass. I was getting a "No such file or directory" error for qwt_compass.h; I fixed this by adding the entire path to the file. Then I was getting an error about "slots" and "signals" in one of the qwt_compass dependencies; this was fixed by changing "slots" to "Q_SLOTS" AND "signals" to "Q_SIGNALS" in that file. Now I get undefined reference errors.
This may not be the place for this, but I have looked everywhere. I even have an open question on ros answers: http://answers.ros.org/question/211846/using-qwt-with-qt_ros/ 
Any help would be appreciated.

edit: Ok, It started to work magically. Here is what I did: In ui_main_window.h change "#include qwtcompass.h" to "#include qwt-qt4/qwt_compass.h". This change has to be repeated every time the .ui file is altered, for now. In qwt_abstract_scale_draw.h the lines "slots" and "signals" must be changed to "Q_SLOTS" and "Q_SIGNALS" respectively. In CMakeLists.txt, "${Qwt_LIBRARIES}" must be added to the list of "target_link_libraries()".

**Comment by stonier** [comment]
Can you do a `find_package` for qwt and then add it to the include directories?

**Comment by stonier** [comment]
I haven't used qwt before and we don't use `qt_ros` any longer (shifted to android and qt remocons with regular qt programs) but I've been using [qcustomplot](http://www.qcustomplot.com/) for graphing recently in a qt graphical monitor. The basics should still be similar as its all just qt-cmake.

The relevant lines to make use of qcustomplot in my `CMakeLists.txt`:

```
find_package(QCustomPlot REQUIRED)
set(QCustomPlot_INCLUDE_DIRS ${QCustomPlot_INCLUDE_DIR})
catkin_package(
    INCLUDE_DIRS include 
    LIBRARIES ${PROJECT_NAME} 
    CATKIN_DEPENDS
        ...
    DEPENDS
        QCustomPlot
        ...
    )
include_directories(
    include
    include/${PROJECT_NAME}  # for convenience
    ${catkin_INCLUDE_DIRS}
    ${QT_INCLUDES}    # list of escaped QtCore, ... subdirs.
    ${QT_INCLUDE_DIR} # the root level qt4 dir
    ${QCustomPlot_INCLUDE_DIR}
)
```

The `package.xml` also needs a rosdep `build_depends` and `rosdepends` for qcustomplot so you can install dependencies automagically.

Then in the ui I make sure I specify a regular widget which I then promote to a `QCustomPlot widget`.

**Comment by stonier** [comment]
Closing since this issue has gone Jurassic and no plan to move on this for now.
