### ISSUE TITLE
unable to locate package ros-indigo-qt-create 

### ISSUE THREAD

**Issue by NahidRM** [stonier/qt_ros#20]
Hello, everytime I entre this command to install this package i get the above message..help?

**Comment by progtologist** [comment]
Which ubuntu version are you using? Can you post the output of this command?
```bash
apt search qt-create
```

**Comment by stonier** [comment]
Likely you are on 16.04 / kinetic and you need ros-kinetic-qt-ros.

If you are still having problems, reopen this issue.
