### ISSUE TITLE
How to test the GUI

### ISSUE THREAD

**Issue by Valveware** [stonier/qt_ros#21]
Hey there, I was wondering if you know a way to test the gui. From what I can tell QTestLib is the framework that's used the most to test a qt gui. But what I can figure out is how I can use this with a project created with catkin_create_qt_pkg . Do you know the steps to do so, or do you have an example of this? If not maybe you know a way to test the ui using a different framework of some sort?

**Comment by stonier** [comment]
I've read about them before, but never used a mock framework for Qt myself. You can add the QTestLib to the Qt components in the CMakeLists.txt, that'll pull in the headers, resources and libraries you'll need to get you started.
