### ISSUE TITLE
Usage on ROS lunar

### ISSUE THREAD

**Issue by aaguiar96** [stonier/qt_ros#23]
Hello. Is that possible to use qt_ros in ROS lunar? If so, how can I do it?

Thanks in advance.

**Comment by stonier** [comment]
Should be fine, assuming no destructive changes in Qt between kinetic and lunar. Just drop the repository into your source workspace. Ask questions here if you have problems.

**Comment by aaguiar96** [comment]
I've done that, but I can't use roscreate-qt-pkg (command not found) and I can't install qt-create/qt-build on Lunar (Unable to locate package ros-lunar-qt-create/build).

Do you have any ideas?

**Comment by stonier** [comment]
Ah, looks like the wiki had some typos in it still which is where I assume you are getting the instructions to run `roscreate-qt-pkg`. It should be `catkin_create_qt_pkg`. I've fixed the [tutorial](http://wiki.ros.org/qt_create/Tutorials/Qt%20App%20Templates?distro=melodic).

**Comment by aaguiar96** [comment]
Ok, it worked. I think you can close the issue.

Thank you very much.

**Comment by stonier** [comment]
:+1:
