### ISSUE TITLE
ROS Melodic support?

### ISSUE THREAD

**Issue by MrBoriska** [stonier/qt_ros#29]
Will be released Melodic version?

**Comment by jstiefel** [comment]
Same question from my side...

**Comment by ShieldQiQi** [comment]
I find it work well on Melodic

**Comment by stonier** [comment]
Bloomed https://github.com/ros/rosdistro/pull/24020.

Haven't done any testing though - let me know if it causes any issues once it's in.

**Comment by stonier** [comment]
[Released](http://repositories.ros.org/status_page/ros_melodic_default.html?q=qt_ros), currently in the testing repo.
