### ISSUE TITLE
Unable to locate package ros-kinetic-qt-create

### ISSUE THREAD

**Issue by DanielSchimpf** [stonier/qt_ros#32]
Hello,

I am running ubuntu 16 with ros kinetic. I am not able to install the package ros-kinetic-qt-create. 
Auto complete only finds the following:
```
dan@dan-Precision-7730:~/tm_ws/src$ sudo apt-get install ros-kinetic-q
ros-kinetic-qt-dotgraph       ros-kinetic-qt-gui-py-common
ros-kinetic-qt-gui            ros-kinetic-qwt-dependency
ros-kinetic-qt-gui-cpp  
```

`apt search qt-create` outputs this: 

 ```
dan@dan-Precision-7730:~/tm_ws/src$ apt search qt-create
Sorting... Done
Full Text Search... Done
ros-indigo-qt-create/trusty 0.2.9-0trusty-20190604-061638-0800 amd64
  Provides templates and scripts for creating qt-ros packages (similar to roscreate-pkg).
```
I have also run "sudo apt update" and "sudo apt upgrade", but it didn't help.

Any idea?

Thanks!

**Comment by stonier** [comment]
Not really - it ought to be there. The ros deb server has it [here](http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-qt-create/).

I am curious why you're apt search is throwing up results from trusty though. That would indicate something is wrong with your package management. Did you do a soft upgrade to go from trusty &rarr; xenial or did you do a fresh install? If it was a soft upgrade, quite possibly some old artifacts are lying around and interfering.

**Comment by DanielSchimpf** [comment]
No, it was a fresh ubuntu 16 install. I did install another kernel though (https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/real_time.md)...

**Comment by stonier** [comment]
Perhaps just check that e.g. `/etc/apt/sources.list.d/ros-latest.list` is pointing at xenial, not trusty.

**Comment by DanielSchimpf** [comment]
This is the content of the file:
"deb http://packages.ros.org/ros/ubuntu trusty main"
So I guess it's pointing to trusty. Can I just replace trusty with xenial?

**Comment by DanielSchimpf** [comment]
I changed it and now can find it. No idea how that file changed. Thanks for your help!
